apiVersion: v1
kind: Service
metadata:
  name: jobs-applications-postgres-service
  namespace: job-application-microservices
spec:
  selector:
    app: jobs-applications-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
