apiVersion: v1
kind: Service
metadata:
  name: jobs-applications-service
  namespace: job-application-microservices
spec:
  selector:
    app: jobs-applications
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
