# Defines a ClusterRole named 'traefik-role' with access to necessary Kubernetes and Traefik resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-role
rules:
  # Core Kubernetes resources
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
  # Networking resources
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  # Traefik-specific CRDs
  - apiGroups: ["traefik.io"]
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - ingressrouteudps
      - ingressroutetcps
      - tlsstores
      - serverstransports
      - serverstransporttcps
      - traefikservices
      - tlsoptions
    verbs: ["get", "list", "watch"]
---

# Binds the 'traefik-role' ClusterRole to the default service account in the 'job-application-microservices' namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: job-application-microservices
roleRef:
  kind: ClusterRole
  name: traefik-role
  apiGroup: rbac.authorization.k8s.io
