version: "3.8"

services:
  auth-service:
    image: emmaekwere/auth-service:latest
    container_name: auth-service
    volumes:
      - ./auth-service:/var/www
    ports:
      - "9007:9000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - db
      - redis
    working_dir: /var/www
    command: >
      sh -c "sleep 10 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=9000"

  db:
    image: postgres:15
    container_name: pgsql-auth
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./auth-service/.env

  redis:
    image: redis:7
    container_name: redis-auth
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kong-database:
    image: postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5433:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migration:
    image: kong:3.4
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    depends_on:
      - kong-database

  kong:
    image: kong:3.4
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - "8000:8000"    # Kong Proxy (http)
      - "8443:8443"    # Kong Proxy (https)
      - "8001:8001"    # Kong Admin API
      - "8444:8444"    # Kong Admin API (https)
    env_file:
      - .env
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always

  job-listing-service:
    image: emmaekwere/job-listing-service:latest
    container_name: job-listing-service
    ports:
      - "5000:5000"
    env_file:
      - ./job-listing-service/.env
    depends_on:
      - job-listing-db
    volumes:
      - ./job-listing-service:/app
    working_dir: /app
    command: sh -c "alembic upgrade head && flask run --host=0.0.0.0 --port=5000"

  job-listing-db:
    image: postgres:15
    container_name: job-listing-db
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ./job-listing-service/.env
    volumes:
      - job_pgdata:/var/lib/postgresql/data

  job-apply-service:
    image: emmaekwere/job-apply-service:latest
    container_name: job-apply-service
    ports:
      - "7001:8000"
    env_file:
      - ./job-apply-service/.env
    depends_on:
      - job-apply-service-db
    volumes:
      - ./job-apply-service:/app
    working_dir: /app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  job-apply-service-db:
    image: postgres:15
    container_name: job-apply-service-db
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - ./job-apply-service/.env
    volumes:
      - job_apply_pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
  redis_data:
  kong_data:
  job_pgdata:
  job_apply_pgdata:
