apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/EmmyAnieDev/Job-Microservice.git
    targetRevision: HEAD
    path: eks-deployment-setup
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: job-application-microservices

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true