apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: job-microservices-cluster
  region: eu-west-3
  version: "1.28"

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 20
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        ebs: true
        efs: true
        cloudWatch: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-load-balancer-controller
