apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: job-application-microservices
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  APP_KEY: eGZIRGd0NkxTR3NVZEdaRkxic0pGWXNkWjJsUVZoMzdoWkRjSHI4bWRpND0=  # Laravel application key used for encryption and session security
  JWT_SECRET: eHl6QjN1dFp1SGtOMmZQUnR3dW5rS2xOanZ1YjRmUkljSE8rT1E4Zz0=