apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: job-application-microservices
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
