apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-listing-postgres-deployment
  namespace: job-application-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-listing-postgres
  template:
    metadata:
      labels:
        app: jobs-listing-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: jobs-listing-config
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jobs-listing-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jobs-listing-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
