apiVersion: v1
kind: Service
metadata:
  name: jobs-listing-service
  namespace: job-application-microservices
spec:
  selector:
    app: jobs-listing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
